services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:8.3-fpm
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql mysqli
      && docker-php-ext-enable pdo_mysql
      && php-fpm"
volumes:
  mysql_data:
    driver: local
